// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: post.proto

package postcodec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Meta          string                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Me            bool                   `protobuf:"varint,4,opt,name=me,proto3" json:"me,omitempty"`
	Post          string                 `protobuf:"bytes,5,opt,name=post,proto3" json:"post,omitempty"`
	Time          int64                  `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	Tag           uint32                 `protobuf:"varint,7,opt,name=tag,proto3" json:"tag,omitempty"`
	Hex           string                 `protobuf:"bytes,8,opt,name=hex,proto3" json:"hex,omitempty"`
	MetaTime      int64                  `protobuf:"varint,9,opt,name=meta_time,json=metaTime,proto3" json:"meta_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBReply) Reset() {
	*x = PBReply{}
	mi := &file_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBReply) ProtoMessage() {}

func (x *PBReply) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBReply.ProtoReflect.Descriptor instead.
func (*PBReply) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

func (x *PBReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PBReply) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PBReply) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *PBReply) GetMe() bool {
	if x != nil {
		return x.Me
	}
	return false
}

func (x *PBReply) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *PBReply) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *PBReply) GetTag() uint32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *PBReply) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

func (x *PBReply) GetMetaTime() int64 {
	if x != nil {
		return x.MetaTime
	}
	return 0
}

type PBPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostHex       string                 `protobuf:"bytes,1,opt,name=post_hex,json=postHex,proto3" json:"post_hex,omitempty"`
	TagId         uint32                 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Replies       []*PBReply             `protobuf:"bytes,4,rep,name=replies,proto3" json:"replies,omitempty"`
	LastTime      int64                  `protobuf:"varint,5,opt,name=last_time,json=lastTime,proto3" json:"last_time,omitempty"`
	TypeId        uint32                 `protobuf:"varint,6,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBPost) Reset() {
	*x = PBPost{}
	mi := &file_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBPost) ProtoMessage() {}

func (x *PBPost) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBPost.ProtoReflect.Descriptor instead.
func (*PBPost) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1}
}

func (x *PBPost) GetPostHex() string {
	if x != nil {
		return x.PostHex
	}
	return ""
}

func (x *PBPost) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *PBPost) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PBPost) GetReplies() []*PBReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *PBPost) GetLastTime() int64 {
	if x != nil {
		return x.LastTime
	}
	return 0
}

func (x *PBPost) GetTypeId() uint32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

var File_post_proto protoreflect.FileDescriptor

const file_post_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"post.proto\x12\tpostcodec\"\xba\x01\n" +
	"\aPBReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\tR\x04meta\x12\x0e\n" +
	"\x02me\x18\x04 \x01(\bR\x02me\x12\x12\n" +
	"\x04post\x18\x05 \x01(\tR\x04post\x12\x12\n" +
	"\x04time\x18\x06 \x01(\x03R\x04time\x12\x10\n" +
	"\x03tag\x18\a \x01(\rR\x03tag\x12\x10\n" +
	"\x03hex\x18\b \x01(\tR\x03hex\x12\x1b\n" +
	"\tmeta_time\x18\t \x01(\x03R\bmetaTime\"\xb4\x01\n" +
	"\x06PBPost\x12\x19\n" +
	"\bpost_hex\x18\x01 \x01(\tR\apostHex\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\rR\x05tagId\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12,\n" +
	"\areplies\x18\x04 \x03(\v2\x12.postcodec.PBReplyR\areplies\x12\x1b\n" +
	"\tlast_time\x18\x05 \x01(\x03R\blastTime\x12\x17\n" +
	"\atype_id\x18\x06 \x01(\rR\x06typeIdB\x11Z\x0fcache/postcodecb\x06proto3"

var (
	file_post_proto_rawDescOnce sync.Once
	file_post_proto_rawDescData []byte
)

func file_post_proto_rawDescGZIP() []byte {
	file_post_proto_rawDescOnce.Do(func() {
		file_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)))
	})
	return file_post_proto_rawDescData
}

var file_post_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_post_proto_goTypes = []any{
	(*PBReply)(nil), // 0: postcodec.PBReply
	(*PBPost)(nil),  // 1: postcodec.PBPost
}
var file_post_proto_depIdxs = []int32{
	0, // 0: postcodec.PBPost.replies:type_name -> postcodec.PBReply
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_post_proto_init() }
func file_post_proto_init() {
	if File_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_post_proto_goTypes,
		DependencyIndexes: file_post_proto_depIdxs,
		MessageInfos:      file_post_proto_msgTypes,
	}.Build()
	File_post_proto = out.File
	file_post_proto_goTypes = nil
	file_post_proto_depIdxs = nil
}
